services:
  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/data:/data/caddy
      - ./Caddyfile:/etc/caddy/Caddyfile
      - meshinfo_output/static-html:/srv
      - ./public/images:/srv/images
    environment:
      - CADDY_AGREE=true
    restart: always

  postgres:
    image: postgres:latest
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    restart: always

  meshinfo:
    image: ghcr.io/meshaddicts/meshinfo:latest
    volumes:
      - meshinfo_output:/app/output
      - ./config.json:/app/config.json
      
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    depends_on:
      - caddy
      - postgres

volumes:
  meshinfo_output:
